[tasks.apply]
dir = "{{cwd}}"
run = "./gradlew spotlessApply"

[tasks.verify]
dir = "{{cwd}}"
run = "./gradlew verifyAll"

[tasks.manual]
dir = "{{cwd}}"
run = "./gradlew runWindowsClient"

[tasks.wsl]
dir = "{{cwd}}"
run = "./gradlew runClient"
