modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "glacage"
version = "0.1.0"
displayName = "Glacage"
authors = "milkeclair"
displayTest = "MATCH_VERSION"
description = '''
Gonna make Minecraft look tasty!
'''

[[dependencies.glacage]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glacage]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "BOTH"
